branches:
  only:
    - master

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq

install:
  - sudo apt-get install build-essential
  - sudo apt-get install -y cmake libsfml-dev 

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make 